### GENERAL ###
namespace: support

replicaCount: 1
image:
  repository: erichough/nfs-server
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 2049

securityContext:
  capabilities:
    add:
      - SYS_ADMIN
      - SETPCAP

volume:
  hostPath: /mnt/nfs
