app:
  replicaCount: 1
  image:
    repository: jellyfin/jellyfin
    tag: latest
    pullPolicy: IfNotPresent

volumes:
  configPath: /mnt/jellyfin/config
  mediaPath: /mnt/media

gpu:
  device: /dev/renderD128
