apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "app.name" . }}-config
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  storageClassName: hostpath
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.volumes.configPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "app.name" . }}-config-claim
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  volumeName: {{ include "app.name" . }}-config
  storageClassName: hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
