app:
  replicaCount: 1
  image:
    repository: mysql
    tag: latest
    pullPolicy: IfNotPresent
  env:
    name: coreos
    password: secret

service:
  port: 3306

volume:
  hostPath: /mnt/mysql-data
