apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql-data
  labels:
    app: mysql-deployment
    {{- include "app.labels" . | nindent 4 }}
spec:
  storageClassName: hostpath
  capacity:
    storage: 12Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.volume.hostPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql-data
  labels:
    app: mysql-deployment
    {{- include "app.labels" . | nindent 4 }}
spec:
  volumeName: pv-mysql-data
  storageClassName: hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
