apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.name" . }}-exports
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data: 
  exports: |
    /nfs-share  *(fsid=0,ro,sync,insecure,all_squash,anonuid=65534,anongid=65534,no_subtree_check,nohide)
