apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.name" . }}-exports
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data: 
  exports: |
    /nfs-share  *(rw,sync,fsid=0,crossmnt,no_subtree_check)
