kind: PriorityClass
apiVersion: scheduling.k8s.io/v1
metadata:
  name: {{ include "app.name" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
value: 5
globalDefault: false
description: "This priority class should be used for nfs-provisioner pods only."
