apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-data
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  storageClassName: hostpath
  capacity:
    storage: 1.8Ti
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.volume.hostPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-data
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  volumeName: pv-mysql-data
  storageClassName: hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1.8Ti
