apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 2049
      targetPort: nfs-tcp
      protocol: TCP
      name: nfs-tcp
    - port: 111
      targetPort: rpc-tcp
      protocol: TCP
      name: rpc-tcp
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
