apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: ClusterIp
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 2049
      protocol: TCP
    - port: {{ .Values.service.port }}
      targetPort: 2049
      protocol: UDP
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
