apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 2049
      protocol: TCP
      name: nfs-tcp
    - port: {{ .Values.service.port }}
      targetPort: 2049
      protocol: UDP
      name: nfs-udp
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
